Marking strings for translation

diff --git a/src/git-issue b/src/git-issue
--- a/src/git-issue
+++ b/src/git-issue
@@ -18,6 +18,7 @@ git issue ls
 
 OPTIONS_SPEC=
 . git-sh-setup
+. git-sh-i18n
 
 OLD_REV=$(git rev-parse --abbrev-ref HEAD)
 ISSUE_BRANCH=$(git config --get issue.branch || echo 'issues')
@@ -63,7 +64,7 @@ git_issue_parse_args () {
 				QUIET=true
 			;;
 			\?)
-				die "Invalid option: -$OPTARG"
+				die $(eval_gettextln "Invalid option: -$OPTARG")
 			;;
 		esac
 	done
@@ -81,8 +82,8 @@ git_issue_get_last_id () {
 }
 
 git_issue_switch_branch () {
-	git_local_branch_exists $ISSUE_BRANCH || die 'Git issue not initialized.'
-	git_have_changes && die "You have unstaged changes.\nPlease commit or stash them."
+	git_local_branch_exists $ISSUE_BRANCH || die $(eval_gettextln 'Git issue not initialized.')
+	git_have_changes && die $(gettextln "You have unstaged changes.\nPlease commit or stash them.")
 
 	git checkout -q $ISSUE_BRANCH
 }
@@ -97,14 +98,14 @@ git_issue_help () {
 }
 
 git_issue_init () {
-	git_local_branch_exists $ISSUE_BRANCH && die 'Git issue already initialized.'
-	git_have_changes && die "Cannot initialized: You have unstaged changes.\nPlease commit or stash them."
+	git_local_branch_exists $ISSUE_BRANCH && die $(gettextln 'Git issue already initialized.')
+	git_have_changes && die $(gettextln "Cannot initialized: You have unstaged changes.\nPlease commit or stash them.")
 
 	git checkout -q --orphan $ISSUE_BRANCH
 	test -n "$(git ls-files)" && git rm -qf $(git ls-files)
-	git commit -q --allow-empty -m 'git issue init'
+	git commit -q --allow-empty -m "$(gettextln 'git issue init')"
 
-	info 'Git issue initialized.'
+	info $(gettextln 'Git issue initialized.')
 }
 
 git_issue_new () {
@@ -122,36 +123,36 @@ type:
 ${description}" >"$id"
 
 	git add "$id"
-	git commit -q -m "Create issue #${id}"
+	git commit -q -m "$(eval_gettextln "Create issue #${id}")"
 
-	info "Issue #${id} created."
+	info $(eval_gettextln "Issue #${id} created.")
 }
 
 git_issue_show () {
 	local id="$1"
 
-	test -f "$id" || die "Issue #${id} doesn't exist"
+	test -f "$id" || die $(eval_gettextln "Issue #${id} doesn't exist")
 	cat $id
 }
 
 git_issue_edit () {
 	local id="$1"
 
-	test -f "$id" || die "Issue #${id} doesn't exist"
+	test -f "$id" || die $(eval_gettextln "Issue #${id} doesn't exist")
 
 	GIT_EDITOR=$(git var GIT_EDITOR)
 	eval "$GIT_EDITOR '$id'"
 
-	git_have_changes && git commit -q -m "Edit issue #${id}" "$id" && info "Issue #${id} saved."
+	git_have_changes && git commit -q -m "$(eval_gettextln "Edit issue #${id}")" "$id" && info $(eval_gettextln "Issue #${id} saved.")
 }
 
 git_issue_rm () {
 	local id="$1"
 
-	test -f "$id" || die "Issue #${id} doesn't exist"
+	test -f "$id" || die $(eval_gettextln "Issue #${id} doesn't exist")
 	git rm -q "$id"
 	git commit -q -m "Delete issue #$id"
-	info "Issue #${id} deleted."
+	info $(eval_gettextln "Issue #${id} deleted.")
 }
 
 git_issue_ls () {
@@ -161,7 +162,7 @@ git_issue_ls () {
 	then
 		grep '^title: .*' $issues | sed 's/title://'
 	else
-		echo 'Nothing to do :)'
+		echo $(gettextln 'Nothing to do :)')
 	fi
 }
 # }}}
@@ -177,7 +178,7 @@ else
 	git_issue_parse_args $*
 	shift $(( OPTIND-1 ))
 
-	function_exists "git_issue_${cmd}" || die "git issue $cmd doesn't exist"
+	function_exists "git_issue_${cmd}" || die $(eval_gettextln "git issue $cmd doesn't exist")
 
 	test $cmd != 'help' -a $cmd != 'init' && git_issue_switch_branch
 	git_issue_${cmd} "$@"
