Reduce branch switching

diff --git a/src/git-issue b/src/git-issue
--- a/src/git-issue
+++ b/src/git-issue
@@ -55,10 +55,6 @@ Available commands:
 . git-sh-setup
 . git-sh-i18n
 
-OLD_REV=$(git rev-parse --abbrev-ref HEAD)
-STASHED=false
-ISSUE_BRANCH=$(git config --get issue.branch || echo 'issues')
-
 COMMAND=
 VERBOSE=false
 GIT_QUIET=
@@ -88,6 +84,10 @@ git_want_color () {
 
 git_get_color () {
 	$COLOR && git config --get-color "$1" "$2"
+}
+
+git_get_current_rev () {
+	git rev-parse --abbrev-ref HEAD
 }
 # }}}
 # {{{ Git issue common
@@ -198,20 +198,24 @@ git_require_clean_work_tree () {
 git_issue_switch_branch () {
 	git_local_branch_exists $ISSUE_BRANCH || die $(eval_gettextln 'Git issue not initialized.')
 
-	if git_have_changes
+	if test $(git_get_current_rev) != "$ISSUE_BRANCH"
 	then
-		git stash save -q 'Git issue switch branch'
-		if test $? -eq 0
+		if git_have_changes
 		then
-			STASHED=true
+			git stash save -q 'Git issue switch branch'
+			if test $? -eq 0
+			then
+				STASHED=true
+			fi
 		fi
-	fi
 
-	git_require_clean_work_tree
-	git checkout -q $ISSUE_BRANCH 2>/dev/null
-	if test $? -ne 0
-	then
-		die $(eval_gettextln 'Unable to switch to issues branch')
+		git_require_clean_work_tree
+
+		git checkout -q $ISSUE_BRANCH 2>/dev/null
+		if test $? -ne 0
+		then
+			die $(eval_gettextln 'Unable to switch to issues branch')
+		fi
 	fi
 }
 
@@ -423,6 +427,10 @@ git_issue_close () {
 	git_issue_edit "$@"
 }
 # }}}
+
+OLD_REV=$(git_get_current_rev)
+STASHED=false
+ISSUE_BRANCH=$(git config --get issue.branch || echo 'issues')
 
 trap 'git_issue_restore_branch' EXIT
 
